name: Eight Workflow
on: 
    workflow_dispatch:
        inputs:
            titleCustom:
                description: Type the Title
                type: string
                required: true
                default: "Hello World"
      

jobs:
    run_first_command:
        runs-on: ubuntu-latest
        steps:
            - name: Event Vars
              run: |
                echo "Title: ${{ inputs.titleCustom }}"