name: Forth Workflow
on:
    workflow_run:
        workflows: [Third Workflow]
        types:
            - completed

jobs:
    success_command:
        runs-on: ubuntu-latest
        if: ${{github.event.workflow_run.conclusion == 'success'}}
        steps:
            - name: Success
              run: echo "Success"
    failure_command:
        runs-on: ubuntu-latest
        if: ${{github.event.workflow_run.conclusion == 'failure'}}
        steps:
            - name: Failure
              run: echo "Failure"


