name: Nineth Workflow
on: 
    repository_dispatch:
        types: [test]
jobs:
    run_first_command:
        runs-on: ubuntu-latest
        steps:
            - name: Event Vars
              run: |
                echo "Title: ${{ github.event.client_payload.titleTest }}"
                echo "Test new comp test 01"