name: Ten Workflow
on: [push]
jobs:
    run_first_command:
        runs-on: ubuntu-latest
        steps:
            - name: Context and Expressions
              id: context-expressions
              run: |
                echo ${{ toJson(github) }}
                echo ${{ toJson(runner) }}
                echo ${{ toJson(job) }}
                echo ${{ toJson(steps) }}